#
# User-defined substitutions:
#   _CLOUDSDK_COMPUTE_ZONE
#   _CLOUDSDK_CONTAINER_CLUSTER
#

steps:
  # Generate a kubeconfig file for the given GKE cluster.
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)

        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
    volumes:
      - name: 'kube'
        path: /kube

  # Build the hashcode container image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/hashcode:${COMMIT_SHA}'
      - '.'

  # Patch the deployment.
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |

        cat <<EOF > patch.yaml
        spec:
          template:
            spec:
              containers:
                - name: hashcode
                  image: gcr.io/${PROJECT_ID}/hashcode:${COMMIT_SHA}
        EOF

        kubectl patch --local -o yaml \
          -f kubernetes/deployment-1.yaml \
          -p "$(cat patch.yaml)"

        kubectl patch --local -o yaml \
          -f kubernetes/deploymen-2.yaml \
          -p "$(cat patch.yaml)"

        kubectl patch --local -o yaml \
          -f kubernetes/deployment-3.yaml \
          -p "$(cat patch.yaml)"

        kubectl patch --local -o yaml \
          -f kubernetes/deployment-4.yaml \
          -p "$(cat patch.yaml)"

        kubectl patch --local -o yaml \
          -f kubernetes/deployment-5.yaml \
          -p "$(cat patch.yaml)"

        kubectl patch --local -o yaml \
          -f kubernetes/deployment-6.yaml \
          -p "$(cat patch.yaml)"

        mv deployment-1.yaml kubernetes/deployment-1.yaml
        mv deployment-2.yaml kubernetes/deployment-2.yaml
        mv deployment-3.yaml kubernetes/deployment-3.yaml
        mv deployment-4.yaml kubernetes/deployment-4.yaml
        mv deployment-5.yaml kubernetes/deployment-5.yaml
        mv deployment-6.yaml kubernetes/deployment-6.yaml

        kubectl apply --recursive -f kubernetes

    volumes:
      - name: 'kube'
        path: /kube

images:
  - 'gcr.io/${PROJECT_ID}/hashcode:${COMMIT_SHA}'
